In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./data/ratings.csv')

In [3]:
df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [4]:
df.drop('timestamp', axis=1, inplace=True)

In [5]:
df.sample(5)

          userId  movieId  rating
321414      2211     3654     4.0
471799      3243     3020     5.0
21478512  139605    56775     3.5
18599900  120525     5633     4.0
23837831  154836      260     4.0

In [6]:
#drop headers
df.to_csv('./data/ratings_clean.csv', sep=',', index=False, header=False)

In [7]:
dfmovies = pd.read_csv('./data/movies.csv')

In [8]:
dfmovies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
dfmovies.to_csv('./data/movies_clean.csv', sep=',', index=False, header=False)